# Generated by Django 5.0.4 on 2024-11-20 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentdashboard', '0002_alter_studentsignin_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentsignin',
            old_name='email',
            new_name='email_model',
        ),
        migrations.RenameField(
            model_name='studentsignin',
            old_name='password',
            new_name='password_model',
        ),
    ]
