# Generated by Django 5.0.4 on 2024-11-20 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentdashboard', '0003_rename_email_studentsignin_email_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsignin',
            name='department_model',
            field=models.CharField(default='CSE', max_length=60),
        ),
        migrations.AddField(
            model_name='studentsignin',
            name='image_model',
            field=models.FileField(default=None, max_length=255, null=True, upload_to='studentdashboard/'),
        ),
        migrations.AddField(
            model_name='studentsignin',
            name='name_model',
            field=models.CharField(default='xyz', max_length=60),
        ),
        migrations.AddField(
            model_name='studentsignin',
            name='parentname_model',
            field=models.CharField(default='abc', max_length=60),
        ),
        migrations.AddField(
            model_name='studentsignin',
            name='phoneno_model',
            field=models.CharField(default='+910000000000', max_length=13),
        ),
        migrations.AddField(
            model_name='studentsignin',
            name='section_model',
            field=models.CharField(default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='studentsignin',
            name='usn_model',
            field=models.CharField(default='1BY23XX000', max_length=10),
        ),
        migrations.AlterField(
            model_name='studentsignin',
            name='email_model',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
